"""add user preferences

Revision ID: 938e6ad4591f
Revises: bda42eff96da
Create Date: 2026-08-14 00:41:30.274752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '938e6ad4591f'
down_revision: Union[str, None] = 'bda42eff96da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
