"""initial

Revision ID: 9a7e21f382e5
Revises: 
Create Date: 2026-06-15 22:23:04.023419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a7e21f382e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
