"""add_user_preferences

Revision ID: bda42eff96da
Revises: d678195271bb
Create Date: 2026-06-27 18:58:52.707232

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'bda42eff96da'
down_revision: str | None = 'd678195271bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_noise', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_space', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('required_tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('radius_km', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'radius_km')
    op.drop_column('users', 'required_tags')
    op.drop_column('users', 'preferred_space')
    op.drop_column('users', 'preferred_noise')
    # ### end Alembic commands ###
