"""nullable hashed_password

Revision ID: d678195271bb
Revises: 9a7e21f382e5
Create Date: 2026-06-18 02:06:29.222895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd678195271bb'
down_revision: Union[str, None] = '9a7e21f382e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
