"""강남/홍대/성수 카페 시드 데이터"""

import asyncio
import json

from sqlalchemy import text

from api.db.database import AsyncSessionLocal
from api.models.cafe import Cafe


CAFES = [
    # ── 강남 ──────────────────────────────────────────────────────────────
    {
        "kakao_id": "kk_gangnam_001",
        "name": "블루보틀 커피 삼성점",
        "address": "서울 강남구 삼성동 157-1",
        "latitude": 37.5125,
        "longitude": 127.0595,
        "phone": "02-6949-2020",
        "kakao_url": "https://place.map.kakao.com/26338954",
        "noise_level": "moderate-noise",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 2,
                "10": 3,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 3,
                "17": 3,
                "18": 4,
                "19": 3,
                "20": 2,
            }
        ),
        "rating": 4.5,
        "review_count": 312,
    },
    {
        "kakao_id": "kk_gangnam_002",
        "name": "카페 드 파리 강남점",
        "address": "서울 강남구 역삼동 826-21",
        "latitude": 37.4996,
        "longitude": 127.0368,
        "phone": "02-555-1234",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "cozy",
        "work_tags": ["work-friendly", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 1,
                "10": 2,
                "11": 3,
                "12": 4,
                "13": 4,
                "14": 3,
                "15": 3,
                "16": 2,
                "17": 2,
                "18": 3,
                "19": 2,
                "20": 1,
            }
        ),
        "rating": 4.2,
        "review_count": 87,
    },
    {
        "kakao_id": "kk_gangnam_003",
        "name": "스타벅스 강남대로점",
        "address": "서울 강남구 강남대로 390",
        "latitude": 37.4954,
        "longitude": 127.0289,
        "phone": "02-501-3705",
        "kakao_url": "https://place.map.kakao.com/8064432",
        "noise_level": "lively",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 4,
                "10": 5,
                "11": 5,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 4,
                "17": 5,
                "18": 5,
                "19": 4,
                "20": 3,
            }
        ),
        "rating": 4.0,
        "review_count": 628,
    },
    {
        "kakao_id": "kk_gangnam_004",
        "name": "텐퍼센트 커피 신사점",
        "address": "서울 강남구 신사동 538-7",
        "latitude": 37.5208,
        "longitude": 127.0225,
        "phone": "02-517-0010",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "natural-light",
        "space_type": "cozy",
        "work_tags": ["work-friendly", "specialty-coffee"],
        "crowd_pattern": json.dumps(
            {
                "10": 2,
                "11": 3,
                "12": 3,
                "13": 4,
                "14": 3,
                "15": 3,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 1,
            }
        ),
        "rating": 4.6,
        "review_count": 145,
    },
    {
        "kakao_id": "kk_gangnam_005",
        "name": "카페 마마스 압구정",
        "address": "서울 강남구 압구정동 448",
        "latitude": 37.5270,
        "longitude": 127.0282,
        "phone": "02-544-7722",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "bright",
        "space_type": "private-booth",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet", "decaf-available"],
        "crowd_pattern": json.dumps(
            {
                "10": 2,
                "11": 3,
                "12": 4,
                "13": 5,
                "14": 4,
                "15": 3,
                "16": 3,
                "17": 3,
                "18": 4,
                "19": 4,
                "20": 3,
            }
        ),
        "rating": 4.3,
        "review_count": 203,
    },
    {
        "kakao_id": "kk_gangnam_006",
        "name": "프릳츠 커피 도곡점",
        "address": "서울 강남구 도곡동 467-5",
        "latitude": 37.4892,
        "longitude": 127.0438,
        "phone": "02-577-3222",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "spacious",
        "work_tags": ["specialty-coffee", "work-friendly", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 3,
                "10": 4,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 3,
                "16": 3,
                "17": 2,
                "18": 2,
            }
        ),
        "rating": 4.7,
        "review_count": 289,
    },
    {
        "kakao_id": "kk_gangnam_007",
        "name": "넥스트도어 강남",
        "address": "서울 강남구 논현동 100-8",
        "latitude": 37.5111,
        "longitude": 127.0298,
        "phone": None,
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "private-booth",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet", "non-coffee"],
        "crowd_pattern": json.dumps(
            {
                "10": 1,
                "11": 2,
                "12": 3,
                "13": 3,
                "14": 3,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 3,
                "19": 2,
            }
        ),
        "rating": 4.4,
        "review_count": 76,
    },
    {
        "kakao_id": "kk_gangnam_008",
        "name": "커피밀 서초점",
        "address": "서울 서초구 서초동 1318-19",
        "latitude": 37.4916,
        "longitude": 127.0076,
        "phone": "02-535-2288",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "08": 2,
                "09": 3,
                "10": 4,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 3,
                "16": 3,
                "17": 3,
                "18": 2,
            }
        ),
        "rating": 4.1,
        "review_count": 154,
    },
    {
        "kakao_id": "kk_gangnam_009",
        "name": "어니언 강남",
        "address": "서울 강남구 청담동 110-14",
        "latitude": 37.5258,
        "longitude": 127.0471,
        "phone": "02-515-3787",
        "kakao_url": None,
        "noise_level": "lively",
        "lighting": "natural-light",
        "space_type": "spacious",
        "work_tags": ["specialty-coffee", "no-laptop"],
        "crowd_pattern": json.dumps(
            {
                "10": 3,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 5,
                "15": 4,
                "16": 4,
                "17": 4,
                "18": 5,
                "19": 5,
                "20": 4,
            }
        ),
        "rating": 4.8,
        "review_count": 512,
    },
    {
        "kakao_id": "kk_gangnam_010",
        "name": "카페 노티드 강남",
        "address": "서울 강남구 강남대로 162길 19",
        "latitude": 37.5042,
        "longitude": 127.0254,
        "phone": "02-548-1972",
        "kakao_url": None,
        "noise_level": "lively",
        "lighting": "bright",
        "space_type": "cozy",
        "work_tags": ["no-laptop", "non-coffee"],
        "crowd_pattern": json.dumps(
            {
                "11": 3,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 4,
                "17": 5,
                "18": 5,
                "19": 5,
                "20": 4,
            }
        ),
        "rating": 4.6,
        "review_count": 744,
    },
    # ── 홍대 ──────────────────────────────────────────────────────────────
    {
        "kakao_id": "kk_hongdae_001",
        "name": "커피 한약방",
        "address": "서울 마포구 서교동 395-99",
        "latitude": 37.5527,
        "longitude": 126.9218,
        "phone": "02-333-4455",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "cozy",
        "work_tags": ["work-friendly", "specialty-coffee", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "12": 2,
                "13": 3,
                "14": 3,
                "15": 3,
                "16": 2,
                "17": 2,
                "18": 3,
                "19": 3,
                "20": 3,
                "21": 2,
            }
        ),
        "rating": 4.5,
        "review_count": 98,
    },
    {
        "kakao_id": "kk_hongdae_002",
        "name": "스타벅스 홍대입구역점",
        "address": "서울 마포구 양화로 188",
        "latitude": 37.5571,
        "longitude": 126.9245,
        "phone": "02-322-7878",
        "kakao_url": "https://place.map.kakao.com/7982028",
        "noise_level": "lively",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 3,
                "10": 4,
                "11": 5,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 4,
                "17": 5,
                "18": 5,
                "19": 5,
                "20": 4,
                "21": 3,
            }
        ),
        "rating": 3.9,
        "review_count": 891,
    },
    {
        "kakao_id": "kk_hongdae_003",
        "name": "앤트러사이트 홍대",
        "address": "서울 마포구 토정로 136",
        "latitude": 37.5497,
        "longitude": 126.9050,
        "phone": "02-322-0009",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "specialty-coffee", "fast-wifi"],
        "crowd_pattern": json.dumps(
            {
                "11": 2,
                "12": 3,
                "13": 4,
                "14": 4,
                "15": 4,
                "16": 3,
                "17": 3,
                "18": 4,
                "19": 4,
                "20": 3,
            }
        ),
        "rating": 4.6,
        "review_count": 421,
    },
    {
        "kakao_id": "kk_hongdae_004",
        "name": "카페 레이어드 합정",
        "address": "서울 마포구 합정동 418-4",
        "latitude": 37.5499,
        "longitude": 126.9136,
        "phone": "02-322-8852",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "cozy",
        "work_tags": ["specialty-coffee", "decaf-available"],
        "crowd_pattern": json.dumps(
            {
                "11": 2,
                "12": 3,
                "13": 4,
                "14": 4,
                "15": 3,
                "16": 3,
                "17": 3,
                "18": 4,
                "19": 3,
                "20": 2,
            }
        ),
        "rating": 4.5,
        "review_count": 267,
    },
    {
        "kakao_id": "kk_hongdae_005",
        "name": "테일러커피 홍대",
        "address": "서울 마포구 서교동 399-23",
        "latitude": 37.5534,
        "longitude": 126.9222,
        "phone": "02-336-5512",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "bright",
        "space_type": "counter-seat",
        "work_tags": ["specialty-coffee", "work-friendly"],
        "crowd_pattern": json.dumps(
            {"09": 2, "10": 3, "11": 3, "12": 4, "13": 4, "14": 3, "15": 3, "16": 2, "17": 2}
        ),
        "rating": 4.4,
        "review_count": 133,
    },
    {
        "kakao_id": "kk_hongdae_006",
        "name": "카페 취미 홍대",
        "address": "서울 마포구 와우산로 94",
        "latitude": 37.5561,
        "longitude": 126.9261,
        "phone": None,
        "kakao_url": None,
        "noise_level": "lively",
        "lighting": "dim",
        "space_type": "cozy",
        "work_tags": ["non-coffee", "no-laptop"],
        "crowd_pattern": json.dumps(
            {"14": 2, "15": 3, "16": 4, "17": 4, "18": 5, "19": 5, "20": 5, "21": 4, "22": 3}
        ),
        "rating": 4.3,
        "review_count": 178,
    },
    {
        "kakao_id": "kk_hongdae_007",
        "name": "인더박스 홍대",
        "address": "서울 마포구 동교동 198-27",
        "latitude": 37.5585,
        "longitude": 126.9289,
        "phone": "02-334-6611",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "natural-light",
        "space_type": "private-booth",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "10": 1,
                "11": 2,
                "12": 3,
                "13": 3,
                "14": 3,
                "15": 3,
                "16": 2,
                "17": 2,
                "18": 3,
                "19": 2,
            }
        ),
        "rating": 4.2,
        "review_count": 89,
    },
    {
        "kakao_id": "kk_hongdae_008",
        "name": "커피 그래프 합정",
        "address": "서울 마포구 합정동 365-10",
        "latitude": 37.5482,
        "longitude": 126.9099,
        "phone": "02-322-0101",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet", "specialty-coffee"],
        "crowd_pattern": json.dumps(
            {
                "09": 2,
                "10": 3,
                "11": 4,
                "12": 4,
                "13": 4,
                "14": 3,
                "15": 3,
                "16": 3,
                "17": 2,
                "18": 2,
            }
        ),
        "rating": 4.4,
        "review_count": 192,
    },
    {
        "kakao_id": "kk_hongdae_009",
        "name": "카페 솔트 홍대",
        "address": "서울 마포구 서교동 358-4",
        "latitude": 37.5541,
        "longitude": 126.9178,
        "phone": None,
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "cozy",
        "work_tags": ["decaf-available", "non-coffee"],
        "crowd_pattern": json.dumps(
            {"12": 2, "13": 3, "14": 4, "15": 4, "16": 3, "17": 3, "18": 4, "19": 4, "20": 3}
        ),
        "rating": 4.1,
        "review_count": 115,
    },
    {
        "kakao_id": "kk_hongdae_010",
        "name": "두물머리 합정",
        "address": "서울 마포구 합정동 375-21",
        "latitude": 37.5469,
        "longitude": 126.9072,
        "phone": "02-325-7799",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "cozy",
        "work_tags": ["work-friendly", "specialty-coffee"],
        "crowd_pattern": json.dumps(
            {"11": 1, "12": 2, "13": 3, "14": 3, "15": 2, "16": 2, "17": 2, "18": 2, "19": 2}
        ),
        "rating": 4.6,
        "review_count": 74,
    },
    # ── 성수 ──────────────────────────────────────────────────────────────
    {
        "kakao_id": "kk_seongsu_001",
        "name": "어니언 성수",
        "address": "서울 성동구 아차산로9길 8",
        "latitude": 37.5447,
        "longitude": 127.0562,
        "phone": "02-1644-1941",
        "kakao_url": "https://place.map.kakao.com/1319530797",
        "noise_level": "lively",
        "lighting": "natural-light",
        "space_type": "spacious",
        "work_tags": ["specialty-coffee", "no-laptop"],
        "crowd_pattern": json.dumps(
            {
                "10": 3,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 5,
                "15": 5,
                "16": 4,
                "17": 4,
                "18": 5,
                "19": 5,
                "20": 4,
            }
        ),
        "rating": 4.8,
        "review_count": 1203,
    },
    {
        "kakao_id": "kk_seongsu_002",
        "name": "대림창고 갤러리 카페",
        "address": "서울 성동구 성수이로 78",
        "latitude": 37.5436,
        "longitude": 127.0593,
        "phone": "02-499-9669",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi"],
        "crowd_pattern": json.dumps(
            {"11": 2, "12": 3, "13": 4, "14": 5, "15": 5, "16": 4, "17": 4, "18": 4, "19": 3}
        ),
        "rating": 4.5,
        "review_count": 387,
    },
    {
        "kakao_id": "kk_seongsu_003",
        "name": "카페 수카라",
        "address": "서울 성동구 성수동2가 289-10",
        "latitude": 37.5423,
        "longitude": 127.0548,
        "phone": "02-498-8429",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "cozy",
        "work_tags": ["work-friendly", "specialty-coffee", "power-outlet"],
        "crowd_pattern": json.dumps(
            {"12": 2, "13": 3, "14": 3, "15": 3, "16": 2, "17": 2, "18": 3, "19": 2}
        ),
        "rating": 4.6,
        "review_count": 156,
    },
    {
        "kakao_id": "kk_seongsu_004",
        "name": "블루보틀 커피 성수점",
        "address": "서울 성동구 왕십리로 115",
        "latitude": 37.5467,
        "longitude": 127.0443,
        "phone": "02-6949-2030",
        "kakao_url": "https://place.map.kakao.com/1721557758",
        "noise_level": "moderate-noise",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 2,
                "10": 3,
                "11": 4,
                "12": 5,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 3,
                "17": 3,
                "18": 4,
                "19": 3,
            }
        ),
        "rating": 4.5,
        "review_count": 428,
    },
    {
        "kakao_id": "kk_seongsu_005",
        "name": "펠트 커피 성수",
        "address": "서울 성동구 성수이로14길 14",
        "latitude": 37.5441,
        "longitude": 127.0578,
        "phone": "02-499-5490",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "natural-light",
        "space_type": "counter-seat",
        "work_tags": ["specialty-coffee", "work-friendly"],
        "crowd_pattern": json.dumps(
            {"09": 2, "10": 3, "11": 3, "12": 4, "13": 4, "14": 3, "15": 3, "16": 2, "17": 2}
        ),
        "rating": 4.7,
        "review_count": 234,
    },
    {
        "kakao_id": "kk_seongsu_006",
        "name": "카페 할아버지공장",
        "address": "서울 성동구 성수동1가 668-26",
        "latitude": 37.5458,
        "longitude": 127.0532,
        "phone": "02-464-0705",
        "kakao_url": None,
        "noise_level": "lively",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["no-laptop", "non-coffee"],
        "crowd_pattern": json.dumps(
            {
                "11": 3,
                "12": 4,
                "13": 5,
                "14": 5,
                "15": 4,
                "16": 4,
                "17": 4,
                "18": 5,
                "19": 5,
                "20": 4,
            }
        ),
        "rating": 4.4,
        "review_count": 562,
    },
    {
        "kakao_id": "kk_seongsu_007",
        "name": "카멜커피 성수",
        "address": "서울 성동구 성수이로7길 27",
        "latitude": 37.5430,
        "longitude": 127.0561,
        "phone": "070-8866-5980",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet", "specialty-coffee"],
        "crowd_pattern": json.dumps(
            {
                "10": 2,
                "11": 3,
                "12": 4,
                "13": 5,
                "14": 4,
                "15": 4,
                "16": 3,
                "17": 3,
                "18": 3,
                "19": 2,
            }
        ),
        "rating": 4.5,
        "review_count": 318,
    },
    {
        "kakao_id": "kk_seongsu_008",
        "name": "카페 시몬느",
        "address": "서울 성동구 성수동2가 277-42",
        "latitude": 37.5419,
        "longitude": 127.0539,
        "phone": None,
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "dim",
        "space_type": "private-booth",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet", "decaf-available"],
        "crowd_pattern": json.dumps(
            {"12": 1, "13": 2, "14": 3, "15": 3, "16": 2, "17": 2, "18": 3, "19": 2, "20": 1}
        ),
        "rating": 4.3,
        "review_count": 67,
    },
    {
        "kakao_id": "kk_seongsu_009",
        "name": "루소 성수",
        "address": "서울 성동구 아차산로 68",
        "latitude": 37.5451,
        "longitude": 127.0571,
        "phone": "02-498-2211",
        "kakao_url": None,
        "noise_level": "moderate-noise",
        "lighting": "natural-light",
        "space_type": "cozy",
        "work_tags": ["specialty-coffee", "work-friendly"],
        "crowd_pattern": json.dumps(
            {"11": 2, "12": 3, "13": 4, "14": 4, "15": 3, "16": 3, "17": 3, "18": 3, "19": 2}
        ),
        "rating": 4.4,
        "review_count": 143,
    },
    {
        "kakao_id": "kk_seongsu_010",
        "name": "카페 온도 성수",
        "address": "서울 성동구 성수이로20길 33",
        "latitude": 37.5436,
        "longitude": 127.0601,
        "phone": "02-499-3344",
        "kakao_url": None,
        "noise_level": "quiet",
        "lighting": "bright",
        "space_type": "spacious",
        "work_tags": ["work-friendly", "fast-wifi", "power-outlet"],
        "crowd_pattern": json.dumps(
            {
                "09": 1,
                "10": 2,
                "11": 3,
                "12": 4,
                "13": 4,
                "14": 3,
                "15": 3,
                "16": 3,
                "17": 2,
                "18": 2,
            }
        ),
        "rating": 4.2,
        "review_count": 109,
    },
]


async def seed():
    async with AsyncSessionLocal() as session:
        # 이미 데이터가 있으면 스킵
        result = await session.execute(text("SELECT COUNT(*) FROM cafes"))
        count = result.scalar()
        if count > 0:
            print(f"이미 {count}개의 카페 데이터가 있습니다. 건너뜁니다.")
            return

        for data in CAFES:
            cafe = Cafe(**data)
            session.add(cafe)

        await session.commit()
        print(f"카페 {len(CAFES)}개 시드 데이터 삽입 완료.")
        print("  - 강남 10개")
        print("  - 홍대/합정 10개")
        print("  - 성수 10개")


if __name__ == "__main__":
    asyncio.run(seed())
